apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-on-k8s
  namespace: default
spec:
  type: Python
  mode: cluster
  image: "abhayhk1/spark-k8s-app:3.0"
  pythonVersion: "3"
  imagePullPolicy: Always
  mainApplicationFile: local:///app/spark-minIO.py
  sparkVersion: "3.1.3"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.3
    serviceAccount: spark
  executor:
    cores: 1
    instances: 2
    memory: "1000m"
    labels:
      version: 3.1.3
